### PR TITLE
Added Header Component

### PR DESCRIPTION
**Pull request by shanehobson**
Note - the colors I've used so far on Header and Navbar used are the default primary and secondary colors for material-ui. At some point we need to create a theme and inject it into our project. You mentioned that you had one from a previous project that may work....would you be able to eiether take a stab at that, or send me the code from your previousb project so I can begin working on a color theme?

### CODE REVIEW

**Comment by alextotheroh** [comment]
https://material-ui.com/customization/themes/#muithemeprovider

That section in particular shows how we can wrap our root component in a MuiThemeProvider.  Other parts of that page show how to set primary and secondary colors and shit in the actual theme

I will try to find the example i did soon

**Comment by alextotheroh** [comment]
So this component also has a redux wrapper but I think you can see my thoughts for Mui theme:

```
import React, { Component } from 'react';
import { Provider } from 'react-redux'
import configureStore from '../redux/store/configureStore';
import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';
import getMuiTheme from 'material-ui/styles/getMuiTheme';
import GatekeeperApp from './GatekeeperApp';
import {
    grey800, grey900, grey400, blue500, grey100, grey500
} from 'material-ui/styles/colors';

const store = configureStore();

export default class ReduxAndThemeWrapper extends Component {

    render() {

        // customize the Material-UI theme
        const customMuiTheme = getMuiTheme({
            palette: {
                primary1Color: grey800,
                primary2Color: grey900,
                primary3Color: grey400,
                accent1Color: blue500,
                accent2Color: grey100,
                accent3Color: grey500
            }
        });

        return (
            <Provider store={store}>
                <MuiThemeProvider muiTheme={customMuiTheme}>
                    <GatekeeperApp />
                </MuiThemeProvider>
            </Provider>
        )
    }
}
```

**Comment by alextotheroh** [comment]
I also just realized this could be totally different for the version of Material UI we're using.  D'oh!

**Comment by shanehobson** [comment]
Awesome, I will be able to put something together based on this. And I actually wrapped our project in a redux wrapper, so that part will be the same. Thanks for getting me this info, will make everything much easier!

**Review by alextotheroh — APPROVED** [review]
HAHA love the branding you came up with, that shit is genius.

**Comment by alextotheroh** [comment]
feel free to merge this PR any time, I almost did but didn't know if you were still adding commits

**Comment by shanehobson** [comment]
Haha thanks man! That stuff's just a suggestion, let me know if you have any ideas.

**Pull request merged**
